### ISSUE TITLE
No fping_* metrics, no errors on Ubuntu 20.04

### ISSUE THREAD

**Issue by mweinelt** [schweikert/fping-exporter#17]
I've set up fping-exporter on an Ubuntu 20.04 machine.

fping is installed and available at `/usr/bin/fping`.
```
root@prometheus:/etc/prometheus# apt policy fping
fping:
  Installed: 4.2-1
  Candidate: 4.2-1
  Version table:
 *** 4.2-1 500
        500 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        100 /var/lib/dpkg/status
root@prometheus:/etc/prometheus# file /usr/bin/fping
/usr/bin/fping: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=51b0f1cefe44ccb7f091e6d0135b00a45bcaec42, for GNU/Linux 3.2.0, stripped
root@prometheus:/etc/prometheus# getcap /usr/bin/fping
/usr/bin/fping = cap_net_raw+ep
```

I've tried both the latest release and https://github.com/schweikert/fping-exporter/commit/7aa628e5d19e616702815fc6730079373304b4aa, Prometheus scrapes them and reports success, but no `fping_` metrics are returned.

I've tried sniffing for the packets that are supposed to go out, i.e. `tcpdump -ni enp9s0 host 8.8.4.4`, but no packets every leave the machine.

I'm running fping-exporter under systemd, but even running it as root on the terminal does not change anything, or log anything.

```ini
# /etc/systemd/system/fping-exporter.service
[Unit]
Description=Prometheus fping Exporter
After=network.target

[Service]
User=prometheus-fping
ExecStart=/var/lib/prometheus-fping/fping-exporter_linux_amd64
# or for the current HEAD
# ExecStart=/var/lib/prometheus-fping/go/bin/fping-exporter

[Install]
WantedBy=multi-user.target
```

I have verified, that the `prometheus-fping` user can use `fping`:

```
# tcpdump -ni ens192 host 8.8.4.4 &
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on ens192, link-type EN10MB (Ethernet), capture size 262144 bytes
# sudo -u prometheus-fping fping 8.8.4.4
11:58:53.721751 IP W.X.Y.Z > 8.8.4.4: ICMP echo request, id 23267, seq 0, length 64
11:58:53.722827 IP 8.8.4.4 > W.X.Y.Z: ICMP echo reply, id 23267, seq 0, length 64
8.8.4.4 is alive
```

My scrape_config looks pretty innocent:

```
  - job_name: fping
    scrape_interval: 60s
    static_configs:
      - targets:
        - 8.8.4.4
        - 8.8.8.8
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 127.0.0.1:9605
```

I even straced the running process, and this is how a single HTTP request looks like:
- unprivileged https://gist.github.com/mweinelt/5eaf1b8befeb0db6938898a413b3931a
- root https://gist.github.com/mweinelt/c96adeb47fe0e940e1b5c3cd0f4f5cee

And I think there is something in there, that would explain this.
